### ISSUE TITLE
[OpenSourceEPID][ReadMe]File extension mismatch

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/epid-verification-service#5]
Link : https://github.com/secure-device-onboard/epid-verification-service/blame/master/build/README.md
We are generating .jar file as stated in cmdDocker.sh.
In ReadMe Line No 31: it says we are generating a .war file were as .jar file is getting created.
Can it be updated to .jar file in Read Me.

**Comment by DukeDavis12** [comment]
Fixed in PR #11
